### ISSUE TITLE
Create About section for repository

### ISSUE THREAD

**Issue by Rixaxtech** [Rixaxtech/makeupApp#1]
The About section of the repository is an important part of the project, as it provides information about the purpose and goals of the project, as well as the team members and contributors. In this issue, you will create the About section for the makeup application guide app repository.

**Comment by maddy020** [comment]
I want to work over this issue
Please give some details over it

**Comment by Rixaxtech** [comment]
Create a short description for this repository to go into the About
section.

**Comment by skippyr** [comment]
Hello, @Rixaxtech. I think you are talking about the `About` that appears on the right side of your repository, am I right? What about put one of the first phrases of your `README.md` file there?

"A web app that helps users apply makeup step by step, using their webcam to provide a live preview of their face."
